### ISSUE TITLE
Gate PRs to `main`

### ISSUE THREAD

**Issue by djzager** [konveyor/operator#130]
Create a `.github/workflows/main.yaml` with basic PR gating tests, ie:

- go build
- docker|podman build image
- go test ./...
- etc

Additionally, this workflow should verify tackle can be installed with the updated operator:
1. [start-minikube](https://github.com/konveyor/tackle2-operator/tree/main/.github/actions/start-minikube)
1. install-tackle will need a mechanism for deploying the updated operator (maybe via kustomize) or by generating the appropriate manifests + index image
1. verify tackle is successfully installed.

**Comment by kaovilai** [comment]
@djzager re: 2, this should be easy if you just fix #201 (optional)  then you can follow what we've done in [oadp-operator](https://github.com/openshift/oadp-operator/blob/fde6240caae9a03ae73bed65ad522790f25054e1/Makefile#L364) to use `operator-sdk run bundle` which will automatically make a catalogsource and create subscription+installplan for you.
