### ISSUE TITLE
Not able to install the tackle operator

### ISSUE THREAD

**Issue by vemularamana** [konveyor/operator#142]
Hi,
I am installing tackle-2 UI in windows 10 machine. following the https://github.com/konveyor/tackle2-operator steps. Using dockerdesktop for kubernetes. When following the "Creating a Tackle CR" step getting "error: resource mapping not found for name: "tackle" namespace: "my-konveyor-tackle" from "STDIN": no matches for kind "Tackle" in version "tackle.konveyor.io/v1alpha1"
ensure CRDs are installed first".

I am unable to get olm pods.
![image](https://user-images.githubusercontent.com/58293162/208045062-8d0fe68e-62d6-4a0a-b22d-dad7d83c37d0.png)

Please help me how to install tackle operator for tacke2-ui

**Comment by srinikr1972** [comment]
Its hanging when i try to do docker pull
![image](https://user-images.githubusercontent.com/121024476/208402767-19160bff-f011-409a-b8ab-da018768548d.png)

**Comment by fbladilo** [comment]
@vemularamana I don't have experience with windows 10 environment k8s environment but at the very least you will need a k8s cluster with OLM support properly running before attempting to deploy Tackle

**Comment by djzager** [comment]
Issue is really old and a lot has changed. Closing this. Please re-open with info about what is going on if it's still a problem with the latest release of https://operatorhub.io/operator/konveyor-operator
