### ISSUE TITLE
Document how to login into Keycloak with keycloak admin credentials 

### ISSUE THREAD

**Issue by chinmayshrikhande** [konveyor/operator#177]
Hi,

Currently, I have the local setup for tackle up and running. I was able to login from the tackle login page using the default credentials and was able to change my credentials.

I am facing a problem while logging into the keycloak administration console. I tried with the default credentials of (admin/admin) and also the changed credentials for tackle, but I am not able to login into keycloak.

Can you please help me with where can I find the credentials for keycloak.

Thanks!

**Comment by jwmatthews** [comment]
@jmontleon @djzager @fbladilo @mansam can you help?

**Comment by jmontleon** [comment]
The admin password is randomly generated and stored in a secret. You can see the credentials by running something like:

`oc -n konveyor-tackle get secret tackle-keycloak-sso -o go-template='{{ index .data "admin-username" | base64decode }} / {{ index .data "admin-password" | base64decode }}{{printf "\n"}}'`

**Comment by jwmatthews** [comment]
Thank you @jmontleon 

I added a 'documentation' label, so we can revisit project docs and be sure this information is clearly communicated for users.

**Comment by chinmayshrikhande** [comment]
Hi @jwmatthews , @jmontleon,

Thank you very much for your help.
I was able to get the key-cloak credentials using following command:
```kubectl -n my-tackle-operator get secret tackle-keycloak-sso -o go-template='{{ index .data "admin-username" | base64decode }} / {{ index .data "admin-password" | base64decode }}{{printf "\n"}}'```

Thanks!

**Comment by jwmatthews** [comment]
Thank you @chinmayshrikhande for following back to confirm.  I'll keep this issue open so we can use it to track updating the documentation.

**Comment by jmontleon** [comment]
Something like this is probably a little easier to read:
`oc -n konveyor-tackle extract secret/tackle-keycloak-sso --to=-`
