### ISSUE TITLE
How can we restrict the users to view only specific applications and their related data

### ISSUE THREAD

**Issue by chinmayshrikhande** [konveyor/operator#202]
Hi,

Currently, I have set up the konveyor tackle locally using Kubernetes by following this guide: https://konveyor.github.io/tackle/installation/

I have created multiple users in keycloak and have assigned them the role of tackle-architect and I am also able to log in using these different users in Tackle.

The problem that I am facing right now is that any application that is created by UserA is also visible to UserB and vice-versa.
Is there a way I can restrict the users to view only specific applications and their related data?

Can you please share your thoughts on this, will be really helpful.
Kindly let me know if this is not the right forum and if I have to ask this question somewhere else.

PS: I have opened the same ticket at: https://github.com/konveyor/konveyor.github.io/issues/12, but did not get any response there. So checking if I can get any help here.

Thanks!

**Comment by jwmatthews** [comment]
Konveyor does not support this today, we have the below RFE open to track this request:
https://github.com/konveyor/enhancements/issues/110

@chinmayshrikhande let's use the above for further conversation on this issue.

**Comment by dymurray** [comment]
Closing as we are tracking in the linked RFE
