### ISSUE TITLE
:seedling: Replace the windup addon with the analyzer-lsp.

### ISSUE THREAD

**Issue by jortel** [konveyor/operator#244]
I think s/windup/analyzer/g should do it.

Also, now that the **hub** is storing analysis data in the DB, we should at least double the default DB volume size of 5G to 10G (or more).  Perhaps 50G.
For 1000 applications, 100 issues, 1500 incidents each, the tackle.db is 4.3G.  I have been using these numbers as a _medium_ sized deployment.
Now that we are no longer storing windup reports in the _bucket_ volume I think we can safely reduce this default of 100G a lot.  Perhaps down to 25G.
Also, given the MUCH more complex queries on large datasets, we should consider bumping the cpu & memory request/limit on the Hub.
```
hub_container_requests_cpu: "100m"
hub_container_limits_cpu: "500m"
hub_container_requests_memory: "350Mi"
hub_container_limits_memory: "800Mi"
```
should be probably be.
```
hub_container_requests_cpu: "500m"
hub_container_limits_cpu: "1"
hub_container_requests_memory: "1Gi"
hub_container_limits_memory: "2Gi"
```
I will try to get better benchmarks.

We may want to have a broader discussion on this. What is our target out-of-the-box deployment?
100 applications on a labtop w/ minikube?
Bigger?  Smaller?

**Comment by jmontleon** [comment]
The bash script is just keying off that for the image name as I recall:
https://github.com/konveyor/operator/blob/main/tools/konveyor-operator-publish-commands.sh#L135

If you're going to change https://github.com/konveyor/operator/pull/247/files#diff-8ac33fe295df086d3e55df1eb01194819d34cc0f5f54076dba96ceac0e40bd79R67 I think you need to update  https://github.com/konveyor/operator/blob/b51f88755b5a44d7588ceecfb4f1a4596da712e3/bundle/manifests/konveyor-operator.clusterserviceversion.yaml#L197
and https://github.com/konveyor/operator/blob/b51f88755b5a44d7588ceecfb4f1a4596da712e3/bundle/manifests/konveyor-operator.clusterserviceversion.yaml#L33 (via the make bundle stuff Tiger fixed I would think would be the right way)

And these should be fixed too though less critical
https://github.com/konveyor/operator/blob/b51f88755b5a44d7588ceecfb4f1a4596da712e3/bundle/manifests/konveyor-operator.clusterserviceversion.yaml#L54-L55

**Comment by jwmatthews** [comment]
Related to https://github.com/konveyor/enhancements/issues/108
