### ISSUE TITLE
Update readme to remove references to tackle2-operator

### ISSUE THREAD

**Issue by savitharaghunathan** [konveyor/operator#246]
ref: https://github.com/konveyor/operator/issues/198

**Comment by punithnayak** [comment]
Hey @savitharaghunathan  can you tell me what exactly should be done

**Comment by savitharaghunathan** [comment]
Hi @punithnayak, The readme has references to tackle2-operator. It needs to be updated to konveyor-operator. Its just a word swap. Please note it might not apply to sample outputs. Hope this helps

**Comment by punithnayak** [comment]
Ok will raise Pr soon

**Comment by punithnayak** [comment]
Should We change all the tackle2-operator references to konveyor-operator

**Comment by punithnayak** [comment]
https://github.com/konveyor/operator/pull/255
@savitharaghunathan
