### ISSUE TITLE
Update create release workflows to account for sequencing needs of dependent images

### ISSUE THREAD

**Issue by pranavgaikwad** [konveyor/operator#250]
We need to sequence the release creation steps such that some images are built in a specified order. This will depend on a [new workflow](https://github.com/konveyor/release-tools/pull/26) we are introducing to automatically update the Dockerfile in a repo when a new release branch `release-X.Y` is created. The idea is to wait until that workflow finishes and updates the Dockerfile, then we begin creating images. 

Images should be built in following order:

```
(1) jdtls-server-base    --->  (2) analyzer-lsp   --->   (3) windup-shim  --->  (4) analyzer-addon
(1) .NET-server         
(1) [any other server]
```

Note that the Dockerfile workflow will need to be enabled on all repos in steps (2) and after.

**Comment by djzager** [comment]
More I think about this...when we create a release branch, this is when we should be locking down the internal go dependencies to the release branch. Some other process will need to update the dependency (ie. tackle2-addon) in the relevant projects (ie. tackle2-addon-analyzer) in the case there was a bug impacting the addon dep.
