### ISSUE TITLE
[LFX Fall '23 Mentorship]: Extend use-case of detecting deprecated Kubernetes API usage

### ISSUE THREAD

**Issue by jwmatthews** [konveyor/operator#251]
This is a LFX mentorship project intended to run in Fall 2023

# Description 

We are looking for help on extending a use-case of detecting usage of [deprecated and removed Kubernetes APIs](https://kubernetes.io/docs/reference/using-api/deprecation-guide/) in applications.  We need help in creating analysis rules that work with our [static code analyzer](https://github.com/konveyor/analyzer-lsp), help to create automated tests to ensure this functionality is working as expected, and documentation to share with the community on how to leverage Konveyor for this scenario.

This work will involve

- determining what API resources have been deprecated or removed in each version of Kubernetes
- building [Analyzer LSP Rules](https://github.com/konveyor/analyzer-lsp/blob/main/docs/rules.md) to be contributed to our [Rulesets repository](https://github.com/konveyor/rulesets)
- curation or development of sample applications in Golang, Java, and YAML to aid test scenarios
- creation of a new test to be integrated into Konveyor's CI 
- documentation to show a guided walkthrough of this capability
 
You can see the beginning of this use-case being addressed with a [sample rule](https://github.com/konveyor/analyzer-lsp/blob/main/rule-example.yaml#L42-L45) in this [demo of analyzer-lsp](https://github.com/konveyor/analyzer-lsp/tree/main#quick-demo). 

The development environment is based on Golang and Kubernetes. A minikube instance will work well for local development on Linux or Mac systems.

## Related Links:
- [Konveyor Contributor Guide](https://github.com/konveyor/community/blob/main/CONTRIBUTING.md)
- [Konveyor Unified Experience](https://github.com/konveyor/enhancements/tree/master/enhancements/unified_experience)
- [Example walk through of Konveyor running an analysis on a Java app](https://github.com/konveyor/example-applications/tree/main)
- [Blog post showing value of Konveyor and Custom Rules](https://www.konveyor.io/blog/modernize-petclinic-to-k8s-using-konveyor/)
- Analysis Engine Repository: [konveyor/analyzer-lsp](https://github.com/konveyor/analyzer-lsp)
- Analysis Rulesets repository: [konveyor/rulesets](https://github.com/konveyor/rulesets) 
- Analysis Rules Development Documentation: https://github.com/konveyor/analyzer-lsp/blob/main/docs/rules.md 

## Projects to consider for inspiration/collaboration/integration:
- https://github.com/devtron-labs/silver-surfer
- https://github.com/rikatz/kubepug
- https://github.com/redhat-developer/yaml-language-server
- https://github.com/FairwindsOps/pluto
- https://github.com/doitintl/kube-no-trouble

**Comment by jwmatthews** [comment]
Note:  https://github.com/rikatz/kubepug may help for seeing how they determine what APIs are deprecated

**Comment by anshgoyalevil** [comment]
@jwmatthews I would research on this issue and design a proposal for the LFX Fall'23. Thanks.

**Comment by jwmatthews** [comment]
Related to: https://github.com/cncf/mentoring/pull/1035

**Comment by punithnayak** [comment]
Hey this project looks cool will defiantly apply when form come up

**Comment by satyampsoni** [comment]
Hello Konveyor team.
This project aligns with my interest and my skills and I would love to contribute to this project and during LFX Fall 2023.
Pls let me know if there is any slack community to join for further communication.
Help will be highly appreciated.

**Comment by kaovilai** [comment]
You can join us on [kubernetes slack](https://kubernetes.slack.com/archives/CR85S82A2)

Need an invitation?
Visit https://slack.k8s.io/ for an invitation.

**Comment by tanayvaswani** [comment]
The idea looks great! If I got the opportunity, I would feel happy to work with the team!

**Comment by AdiAkhileshSingh15** [comment]
Hey,
I'm really interested in this project and I plan to apply as a Mentee once LFX Fall applications are open. 
Also, I'm curious to know if there are any beginner-friendly issues available for me to start contributing and get to know more about Konveyor.
Any help would be highly appreciated.
Thanks!

**Comment by vishalrajofficial** [comment]
I am Vishal Raj, a final year CSE student. The LFX Falls CNCF - LitmusChaos project focusing on improving litmusctl UX and codebase and adding new functionalities excites me. I look forward to contributing to this mentorship project by extending the use-case of detecting deprecated and removed Kubernetes APIs. Creating analysis rules, developing automated tests, and providing comprehensive documentation for the community will be my primary areas of focus. Let's work together to enhance LitmusChaos and create valuable contributions to the CNCF ecosystem!

**Comment by vishalrajofficial** [comment]
I am Vishal Raj, a final year CSE student. The CNCF - Konveyor project to extend the use-case of detecting deprecated Kubernetes API usage excites me. I'm eager to contribute to this mentorship project by creating analysis rules, developing automated tests, and providing documentation for leveraging Konveyor to detect deprecated and removed Kubernetes APIs. Building Analyzer LSP Rules and curating sample applications will be my focus. Let's collaborate to enhance Konveyor and support the Kubernetes community with valuable tools and resources!

**Comment by jwmatthews** [comment]
Note:  https://github.com/devtron-labs/silver-surfer may help or at least knowing how they approach problem could be useful.

Thank you @savitharaghunathan for this suggestion

**Comment by jwmatthews** [comment]
Thank you @Parthiba-hazra for recommending we look at: https://github.com/FairwindsOps/pluto

https://kubernetes.slack.com/archives/C04QZJFQ0UA/p1690994666561419

Appreciate the tip!

**Comment by djzager** [comment]
@jwmatthews What's the status of this issue? Is it done? Should it be moved to another repo?

**Comment by jwmatthews** [comment]
Closed via https://github.com/konveyor/analyzer-lsp/pull/441
