### ISSUE TITLE
Support upgrade from 0.2.x -> 0.3.x with migration of pathfinder assessments

### ISSUE THREAD

**Issue by dymurray** [konveyor/operator#264]
With 0.3.0, the assessments are stored in a new format, and we want the operator to support the automatic migration of pathfinder assessments to the new assessment format.

Pathfinder will be replaced by functionality in the Hub.  The operator needs to:
1. Export assessments (from pathfinder).
2. Update tackle deployments.
3. Wait for pods/containers to be restarted.
4. Import assessments.
5. Delete all pathfinder related resources.

Assessment export/import will be performed using the hub export/import tool.  The operator dockerfile needs to be updated to include the tool.

Requires: https://github.com/konveyor/tackle2-hub/issues/489

**Comment by aufi** [comment]
CLI script already merged to operator: https://github.com/konveyor/operator/pull/269

**Comment by djzager** [comment]
Closing as https://github.com/konveyor/operator/pull/276 has merged

**Comment by jmontleon** [comment]
Resolved by https://github.com/konveyor/operator/pull/276
