### ISSUE TITLE
Support multiple providers.

### ISSUE THREAD

**Issue by jortel** [konveyor/operator#313]
In support multiple providers, the CRDs found [here](https://github.com/konveyor/tackle2-hub/tree/main/k8s/api/tackle/v1alpha1) have changed.  See [pull/606](https://github.com/konveyor/tackle2-hub/pull/606) for latest files.

The installed CRs have also changed found [here](https://github.com/konveyor/tackle2-addon-analyzer/blob/main/hack/addon.yaml).  See:  [pull/79](https://github.com/konveyor/tackle2-addon-analyzer/pull/79) for latest files.

The separation of analyzer and providers mean the addon-analyzer no longer needs as much cpu and memory.  

The current variables (and defaults) really apply to the java provider (extension).  Let's discuss how to deal with this.
```
analyzer_container_limits_cpu: "1"
analyzer_container_limits_memory: "4Gi"
analyzer_container_requests_cpu: "1"
analyzer_container_requests_memory: "4Gi"
```
probably needs new variables?
```
provider_java_container_limits_cpu: "1"
provider_java_container_limits_memory: "4Gi"
provider_java_container_requests_cpu: "1"
provider_java_container_requests_memory: "4Gi"
```

**Comment by jmontleon** [comment]
@jortel do I understand correctly that we should be replacing:
https://github.com/konveyor/operator/blob/main/roles/tackle/templates/customresource-addon-analyzer.yml.j2

with a templatized version of:
https://github.com/konveyor/tackle2-addon-analyzer/pull/79/files#diff-cee5d263c7c9eac225a178f916e817e348740f30c11dcfbc28fb3e432684f3b3

or am I off target.

**Comment by jortel** [comment]
> @jortel do I understand correctly that we should be replacing: https://github.com/konveyor/operator/blob/main/roles/tackle/templates/customresource-addon-analyzer.yml.j2
> 
> with a templatized version of: https://github.com/konveyor/tackle2-addon-analyzer/pull/79/files#diff-cee5d263c7c9eac225a178f916e817e348740f30c11dcfbc28fb3e432684f3b3
> 
> or am I off target.

Correct.
